export const OFFLOADED_TOOL_NAMES = [
	// browser
	"browser_open",
	"browser_snapshot",
	"browser_click",
	"browser_fill",
	"browser_type",
	"browser_press",
	"browser_frame",
	"browser_get",
	"browser_wait",
	"browser_screenshot",
	"browser_close",
	"browser_state_save",
	"browser_state_load",
	// mermaid
	"mermaid_render_svg",
	"mermaid_render_ascii",
	// memory
	"memory_read",
	"memory_append",
	"memory_write",
	"memory_search",
	// web
	"web_search",
	"firecrawl_search",
	"firecrawl_scrape",
	"firecrawl_map",
	"firecrawl_crawl",
	"firecrawl_batch_scrape",
	"firecrawl_extract",
	"firecrawl_poll",
	"firecrawl_status",
	"firecrawl_cancel",
	"google_public_doc_read",
	"google_public_sheet_read",
	"google_public_slides_read",
	// tracker
	"yandex_tracker_search",
	"yandex_tracker_find_issue",
	"yandex_tracker_issue_summary",
	// jira
	"jira_search",
	"jira_sprint_issues",
	"jira_issues_find",
	"jira_issue_get",
	"jira_issue_get_comments",
	// figma
	"figma_me",
	"figma_file_get",
	"figma_file_nodes_get",
	"figma_file_comments_list",
	"figma_project_files_list",
	// wiki
	"yandex_wiki_find_page",
	"yandex_wiki_read_page",
	"yandex_wiki_update_page",
	"yandex_wiki_append_page",
	"wiki_page_get",
	"wiki_page_get_by_id",
	"wiki_page_create",
	"wiki_page_update",
	"wiki_page_append_content",
	// posthog
	"actions-get-all",
	"action-get",
	"dashboards-get-all",
	"dashboard-get",
	"docs-search",
	"error-details",
	"list-errors",
	"event-definitions-list",
	"properties-list",
	"experiment-get",
	"experiment-get-all",
	"experiment-results-get",
	"feature-flag-get-all",
	"feature-flag-get-definition",
	"insight-get",
	"insight-query",
	"insights-get-all",
	"query-generate-hogql-from-question",
	"query-run",
	"get-llm-total-costs-for-project",
	"logs-list-attribute-values",
	"logs-list-attributes",
	"logs-query",
	"organization-details-get",
	"organizations-get",
	"projects-get",
	"property-definitions",
	"entity-search",
	"survey-get",
	"survey-stats",
	"surveys-get-all",
	"surveys-global-stats",
] as const;

export type OffloadedToolName = (typeof OFFLOADED_TOOL_NAMES)[number];

export function isOffloadedTool(name: string): name is OffloadedToolName {
	return (OFFLOADED_TOOL_NAMES as readonly string[]).includes(name);
}
